@echo off
echo Starting the Hyper server...
echo Activating virtual environment...
call venv\Scripts\activate

echo Launching the application in a new window...
start "" python app/main.py

echo Opening the application in your default web browser...
start http://127.0.0.1:8000

pause
